// Generated by CoffeeScript 1.3.3

$(function() {
  $('.flash.fatal').addClass('alert alert-error');
  $('.flash.info').addClass('alert alert-success');
  return $('.flash.warning').addClass('alert alert-info');
});

$(function() {
  return $('#flash').effect('fade', {}, 500000);
});
